<?php
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 */

/** Horus Hiero
 * 
 * @file api/index.php  
 * @author Per Löwgren
 * @date Modified: 2016-01-07
 * @date Created: 2016-01-07
 */

use Horus\HorusNode;
use Horus\HorusHiero;
use Horus\HorusHTML;

$BASE_URL = '../';  // Set to URL where images and style sheets can be found
$HEADER   = '';
$FOOTER   = '';

if(count($argv)) {
	$args = array();
	for($i=0; $i<count($argv); ++$i) {
		$a = $argv[$i];
		if(strncmp($a,'-font=',6)===0) $args['font'] = substr($a,6);
		elseif(strncmp($a,'-mcd=',5)===0) $args['mcd'] = substr($a,5);
		elseif(strncmp($a,'-text=',6)===0) $args['text'] = substr($a,6);
		elseif(strncmp($a,'-height=',8)===0) $args['height'] = substr($a,8);
		elseif($a=='-lines') $args['lines'] = true;
	}
} elseif(count($_REQUEST)) {
	$args = &$_REQUEST;
	$HEADER = <<<END
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Horus Hireoglyphic</title>
<link type="text/css" href="{$BASE_URL}hiero.css" rel="stylesheet" />
</head>
<body>
END;
	$FOOTER = <<<END
</body>
</html>
END;
}

if(isset($args['mdc'])) $text = $args['mdc'];
elseif(isset($args['text'])) $text = $args['text'];
else $text = file_get_contents('php://input');

if(!$text) die;

require_once __DIR__.'/Horus/HorusHiero.php';
require_once __DIR__.'/Horus/HorusHTML.php';
require_once __DIR__.'/Horus/HorusNode.php';

$font    = isset($args['font'])?   $args['font']   : HIERO_DEFAULT_FONT;
$height  = isset($args['height'])? $args['height'] : HIERO_DEFAULT_HEIGHT;
$lines   = isset($args['lines'])?  $args['lines']  : HIERO_DEFAULT_LINES;

require_once __DIR__.'/phonemes.php';
require_once __DIR__."/metrics-{$font}.php";

echo $HEADER;

echo HorusHiero::parse($text,array(
	'font'=>$font,
	'output'=>'html',
	'font-url'=>"{$BASE_URL}{$font}/",
	'height'=>$height,
	'lines'=>$lines,
	'comment'=>'Generated by HorusHiero',
));

echo $FOOTER;